GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvdSIsImlhdCI6MTYyMjE1MDQwNCwiZXhwIjoxNjIyMTU5MTA0fQ.bXedUCdXAF2qFwMECTvomH5rInZaqvH7mZ-BDWMyDRU

###

POST http://localhost:3000/login
Content-Type: application/json

{"username":"lou"}